UPDATE public.analyses
SET
  security_issues = jsonb_build_array(
    jsonb_build_object(
      'id','det-q-1','severity','critical','category','payment_validation',
      'title','Premium check is permanently turned on',
      'you_said','src/routes/dashboard.tsx line 30 hardcodes a permission flag to true. Every user gets premium access.',
      'what_was_built','src/routes/dashboard.tsx line 30 hardcodes a permission flag to true. Every user gets premium access.',
      'business_impact','Paid features are free for everyone. You lose revenue.',
      'explanation','src/routes/dashboard.tsx line 30 hardcodes a permission flag to true. Every user gets premium access.',
      'status','failed',
      'what_we_found','src/routes/dashboard.tsx line 30 hardcodes a permission flag to true. Every user gets premium access.',
      'what_this_means','Paid features are free for everyone. You lose revenue.',
      'how_to_fix','Replace the hardcoded flag with a real check: read the current user, query profiles.plan, set the flag based on that value.',
      'fix_prompt','Replace the hardcoded flag in src/routes/dashboard.tsx line 30 with a real check: read the current user, query profiles.plan, set the flag based on that value.',
      'technical_reference','payment_validation','google_query','payment_validation supabase fix',
      'confidence','verified','confidence_reason','Promoted from the code-reading stage which cited the exact file and line.',
      'file_path','src/routes/dashboard.tsx','line_number',30,
      'code_snippet','File: src/routes/dashboard.tsx, Line 30: `const isPro = true;` implies AI summary is available to all',
      'evidence','Hardcoded permission flag flagged in code understanding.','source','deterministic'
    ),
    jsonb_build_object(
      'id','det-q-2','severity','critical','category','rls',
      'title','Anyone can read everyone else''s data',
      'you_said','src/routes/dashboard.tsx line 33 runs a database query with no user filter. It returns every row to every visitor.',
      'what_was_built','src/routes/dashboard.tsx line 33 runs a database query with no user filter. It returns every row to every visitor.',
      'business_impact','Every user sees every other user''s records on this page.',
      'explanation','src/routes/dashboard.tsx line 33 runs a database query with no user filter. It returns every row to every visitor.',
      'status','failed',
      'what_we_found','src/routes/dashboard.tsx line 33 runs a database query with no user filter. It returns every row to every visitor.',
      'what_this_means','Every user sees every other user''s records on this page.',
      'how_to_fix','Add .eq(''user_id'', user.id) to the query, then enable row-level rules on the table in Supabase.',
      'fix_prompt','Open src/routes/dashboard.tsx line 33. Add .eq(''user_id'', user.id) to the query, then enable row-level rules on the notes table in Supabase with policy USING (auth.uid() = user_id).',
      'technical_reference','rls','google_query','rls supabase fix',
      'confidence','verified','confidence_reason','Promoted from the code-reading stage which cited the exact file and line.',
      'file_path','src/routes/dashboard.tsx','line_number',33,
      'code_snippet','File: src/routes/dashboard.tsx, Line 33: `supabase.from("notes").select("*")` fetches all notes',
      'evidence','Unfiltered query flagged in code understanding.','source','deterministic'
    ),
    jsonb_build_object(
      'id','det-q-3','severity','critical','category','admin_access',
      'title','Anyone can open your admin page',
      'you_said','src/routes/admin.tsx line 11 is an admin route with no login or role check.',
      'what_was_built','src/routes/admin.tsx line 11 is an admin route with no login or role check.',
      'business_impact','Any visitor who knows the URL reaches the admin dashboard.',
      'explanation','src/routes/admin.tsx line 11 is an admin route with no login or role check.',
      'status','failed',
      'what_we_found','src/routes/admin.tsx line 11 is an admin route with no login or role check.',
      'what_this_means','Any visitor who knows the URL reaches the admin dashboard.',
      'how_to_fix','Add a login + admin role check at the top of src/routes/admin.tsx.',
      'fix_prompt','Add a login + admin role check at the top of src/routes/admin.tsx. If there is no user or the user is not an admin, redirect to / before rendering anything.',
      'technical_reference','admin_access','google_query','admin_access supabase fix',
      'confidence','verified','confidence_reason','Promoted from the code-reading stage which cited the exact file and line.',
      'file_path','src/routes/admin.tsx','line_number',11,
      'code_snippet','File: src/routes/admin.tsx, Line 11: Comment indicates no authentication check for the /admin route.',
      'evidence','Open admin route flagged in code understanding.','source','deterministic'
    ),
    jsonb_build_object(
      'id','det-q-4','severity','critical','category','secret_exposure',
      'title','Database master key is in your frontend code',
      'you_said','src/integrations/supabase/client.server.ts uses the service role key. This key bypasses every database rule.',
      'what_was_built','src/integrations/supabase/client.server.ts uses the service role key. This key bypasses every database rule.',
      'business_impact','Anyone who opens your site in dev tools can read or delete all data.',
      'explanation','src/integrations/supabase/client.server.ts uses the service role key.',
      'status','failed',
      'what_we_found','src/integrations/supabase/client.server.ts uses the service role key. This key bypasses every database rule.',
      'what_this_means','Anyone who opens your site in dev tools can read or delete all data.',
      'how_to_fix','Move the operation into a Supabase Edge Function. The frontend must only use the anon key.',
      'fix_prompt','Move the operation in src/integrations/supabase/client.server.ts into a Supabase Edge Function. The frontend must only use the anon key. Then rotate the service role key.',
      'technical_reference','secret_exposure','google_query','secret_exposure supabase fix',
      'confidence','verified','confidence_reason','Promoted from the code-reading stage which cited the exact file and line.',
      'file_path','src/integrations/supabase/client.server.ts','line_number',1,
      'code_snippet','Refers to server-side client with service role key for admin operations that bypasses RLS',
      'evidence','Service role key reference flagged in code understanding.','source','deterministic'
    )
  ),
  intent_match_score = 0,
  security_score = 0,
  summary = 'Backfilled under the new deterministic-overlay scoring (2026-04). Four critical security issues were promoted from the code-reading stage: open admin route, unfiltered notes query, hardcoded isPro=true, and service role key in frontend code. Combined with the 1 critical and 2 lower-severity business gaps already on file, the app sits at 0/100 — these are the issues your AI built that need to be fixed before any user signs up.'
WHERE id = '37175815-9e04-439d-a7b3-451ce598cb2e';